services:
  fastapi-app:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - .venv:/fastapi/.venv 

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - "8001:8001"
    command: ["poetry", "run", "mkdocs", "serve", "--dev-addr=0.0.0.0:8001"]
