@startuml usecase diagram
left to right direction

actor 教務

package [UCP04]時間割一覧操作 {
    教務--->([UC0401] 時間割をダウンロードする)
    教務--->([UC0402] 時間割をアーカイブする)
    教務--->([UC0403] アーカイブした時間割を稼働中にする)
}

@enduml