@startuml usecase diagram
left to right direction

actor 教務

package "UCP03 年間データ修正" {
    教務--->([UC0301] 曜日時限を編集する)
    教務--->([UC0302] 教員情報を編集する)
    教務--->([UC0303] 教員を削除する)
    教務--->([UC0304] 教員の勤怠を修正する)
    教務--->([UC0305] 科目情報を編集する)
    教務--->([UC0306] 科目を削除する)
    教務--->([UC0307] カリキュラムを修正する)

    ([UC0307] カリキュラムを修正する) ..> ([UC0311] 講座を削除する) : <<extends>>
    ([UC0307] カリキュラムを修正する) ..> ([UC0310] 講座情報を編集する) : <<extends>>
    ([UC0307] カリキュラムを修正する) ..> ([UC0309] ブロックを削除する) : <<extends>>
    ([UC0307] カリキュラムを修正する) ..> ([UC0308] 学級を削除する) : <<extends>> 
}
@enduml
