@startuml usecase diagram
left to right direction

:教務:

    package [UCP02]年間時間割編成 {
        教務--->([UC0201]制約条件を課す（組み込み）)
        教務--->([UC0202]制約条件を課す（チャット）)
        教務--->([UC0203]編成を実行する)
        教務--->([UC0204]編成結果を見る)
        教務--->([UC0209]制約条件を緩和する)
        教務--->([UC0214]コマを入れ替える)
        教務--->([UC0215]承認前の時間割をダウンロードする)
        教務--->([UC0216]時間割を承認する)

        ([UC0204]編成結果を見る) <|-- ([UC0205]学級ビューを見る)
        ([UC0204]編成結果を見る) <|-- ([UC0206]教員ビューを見る)
        ([UC0204]編成結果を見る) <|-- ([UC0207]教室ビューを見る)
        ([UC0204]編成結果を見る) <|-- ([UC0208]統計ビューを見る)

        ([UC0209]制約条件を緩和する) ..> ([UC0213]制約条件の内容を変更する（チャット）) : include
        ([UC0209]制約条件を緩和する) ..> ([UC0212]制約条件の内容を変更する（組み込み）) : include
        ([UC0209]制約条件を緩和する) ..> ([UC0211]制約条件を追加する) : include
        ([UC0209]制約条件を緩和する) ..> ([UC0210]制約条件を除外する) : include

    }

@enduml